### ISSUE TITLE
Collections API Proposal Notes : Siblings ?

### ISSUE THREAD

**Issue by PonteIneptique** [distributed-text-services/collection-api#36]
Hey all,
I really like @hcayless 's proposal because it simplifies a lot the architecture as well as avoiding to much anonymous nodes here and there.
What I would like to know if how would you treat, in this context, unordered inventories collection, because right now you only have `prev` and `next` ? Could we have a siblings-and-self properties maybe ?

**Comment by hcayless** [comment]
I've been grappling a bit with the question of "orderedness". I decided
that collections might have all sorts of order, including ones that are
imposed by the client, if the collection is sortable. So if there is a
natural order, items will have previous and next properties, but otherwise,
if you want all siblings, you need to use parent/members.

I'm not sure truly un-ordered collections are really desirable, because
that would rule out paging. And given that most back end systems will
impose some default order if none is specified, it would actually be hard
to get rid of. My feeling is that all collections are ordered, but that
order may or may not be significant.

**Comment by PonteIneptique** [comment]
Well, this is fine to me to go back to the parents for unordered collections. You could always ask to expand the parent if necessary to get access.
I also feel like having something like

```
dts:siblings-and-self: [{dts:id:<id>, ...}, {dts:id: <selfId>}, {dts:id:<id>, ...}]
```
or simply siblings would be appealing to some people. Might be wrong
