### ISSUE TITLE
collection["members"] and pagination

### ISSUE THREAD

**Issue by PonteIneptique** [distributed-text-services/collection-api#43]
As of now, we have according to Swagger specs :

```json
  "members": {
    "contents": [
      {
        "@id": "urn:cts:latinLit:phi0959.phi005.perseus-lat2",
        "type": "http://homermultitext.org/rdfvocab/edition",
        "model": "http://dts.org/model"
      }
    ],
    "next_cursor": "21-30",
    "prev_cursor": "1-20"
  },
``` 
Most of all, I would change : 
1. prev-cursor and next-cursor properties changed to prev / next.
2. Add `current`
3. Replace their value with absolute or relative uris. Even more if as swagger currently states this is up to implementer

But, generally, I am not really fond of the semantic behind this, mixing up relationships with cursor. I would rather have a `member-cursor` property or even more something that would change the state of the reply, ie : 

```json
{
  "status": {
    "prev-cursor": "1-20",
    "next-cursor": "41-60"
  },
  `object`: {
    "@id"...
  }
}
```

or have the object merged with current system of CollectionResultSet (ie Collection inherits CollectionsResultSet) : 

```json
{
    "prev-cursor": "1-20",
    "next-cursor": "41-60",
    "members": [list]
    "@id"...
}
```

**Comment by balmas** [comment]
The point in CollectionResultSet was to have a standard structure to return for requests that might return one or more than one collections

The reason it's not just an array was so that we could offer a means for pagination across requests. This would only be possible for implementations which had some means of storing state though, so they have to be optional, and each implementation might do a different thing. This is why I suggested using the more generic term "cursor" rather than page etc. because it might be done differently depending upon the implementation. E.g. maybe it's just a UUID into a stored set of results.  I used the twitter api as a model for that.

But in the end, if it's not needed, I'm open to dropping it.  Re-reading @PonteIneptique 's comments above, I think I missed the point about merging the collection and collection result set object -- that doesn't make sense to me, at least not wrt to the original intention behind these objects.

**Comment by hcayless** [comment]
I think it's still not a cursor, at least not in my understanding of the term from databases, i.e. basically an iterator over result sets. And the implementation need not store client state in order to provide paging. A Solr-based implementation wouldn't, for example. It would just re-run the query and give you the next chunk you asked for (granted, a smart implementation would do some caching). Paging does, of course, imply that there's a stable sort order, and maybe we ought to say something about that in the spec.

I'm not advocating dropping anything at this point, just trying to understand the proposal. So /collections would actually give you a flattened list of all the collections in a system? What's the use case for that?

**Comment by balmas** [comment]
no, /collections would not give you a flattened list, just the list of all the collections which are top-level parents.

Some implementations will just have a few here (e.g. such as in cts for which the top level is just the namespaces) but others might have thousands of top-level parents. 

It depends upon the initial query whether this is a cursor over results or pagination doesn't it? If you used filtering parameters, you would end up with something more like a database resultset than just pure pagination.

Again, some of this terminology comes from my derivation of the RDA collections API to produce the DTS API proposal. If we don't want to be that generic with DTS it's totally fine.

**Comment by hcayless** [comment]
Right, I guess I'd hope that an implementation with thousands of anything would be polite enough to organize them a bit—there'd be nothing to stop them from putting their collections into buckets—just like with files on a file system, when things start to get unwieldy, you impose a folder hierarchy. But maybe not...

In any case, I can see the use of result sets as query responses. I guess the real question is whether everything is a query—that's tended to be my personal strategy for systems like this, but it doesn't have to be.

But I can only understand "cursor" as a cursor over pages. Is that how you mean it? A cursor gives you the means to access items in sequence, not to chunk through a set of data. And page size might vary (e.g. I could ask for /1-100, and then I'd expect "next" to be "101-200"). In SQL terms, we're talking about OFFSET and LIMIT, which certainly might be implemented with a cursor, but don't themselves constitute a cursor.

Anyway, sorry if I'm being irritating. I tend to get hung up on terminology. Sometimes it's a good thing, but sometimes it just annoys everybody else :-).

**Comment by balmas** [comment]
I would never begrudge requests for clarity on terminology. If the meaning isn't clear, then usually the terminology needs to be changed. I am not at all wedded to the cursor term.

Please feel free to send a PR for which alternative term make the most sense to you!

**Comment by PonteIneptique** [comment]
I'll but I'd prefer for the current PR to be set in stone. Technically, I have no paging atm so it could wait
