### ISSUE TITLE
Have Passage Identifier reserved characters for expliciting hierarchies and range

### ISSUE THREAD

**Issue by PonteIneptique** [distributed-text-services/collection-api#75]
Currently, CTS has two reserved character when it comes to range : 

- `.` are used to express hierarchy : `1.2.3` is subsubpassage 3 in subpassage 2 in passage 1
- `-` are used to express range : `1-2` means passage *1 to 2*, `1.1-2.5` means passage `1.1` to passage `2.5`

I see the problem of having reserved character but I also think this system has good sides and are not that restrictive. 
At the very least, if we'd remove the technical sense of `-`, we need a `range` parameter in all API supporting queries on Passage.

**Comment by hcayless** [comment]
Would we prohibit `-` and `.` other than as range or hierarchical delimiter? Or insist that other uses be escaped? E.g. `\.`.

**Comment by PonteIneptique** [comment]
That's a good question. My first reaction is yes, because that means we need to be more cautions at parsing (instead of simply being able to do ".split()" ;) ), my second reaction is if this would make people agree with this scheme, I am fine.

**Comment by balmas** [comment]
But I think we would need to be clear that the '-' restriction would apply ONLY to the passage part of an identifier.

**Comment by PonteIneptique** [comment]
`passage.id` and `document.id` being separated in DTS (unlike CTS), I completely agree with this last statement : these restriction in sense and use are only valid for Passages ID

**Comment by jonathanrobie** [comment]
We will use query parameters `start` and `end` instead of specifying range in an identifier.   

In CTS, a passage identifier can correspond to a range, and an implementation should return the corresponding passage for any valid CTS passage identifier.  However, DTS does not specify the semantics of identifiers, this behavior is simply the result of returning a passage corresponding to a CTS identifier.
